<div class="flow-checkout">
    <form method="post" action="<?php if(!empty($this->payment)) echo $this->url('m_cart/default', array('action'=>'submitvirtual')); ?>">

    <section id="accordion" class="ect-margin-tb ect-padding-lr checkout-select">
        <a class="collapsed">
            <p><b><?php echo $this->translate('支付方式'); ?></b><span class="label ect-bg-colory"><?php echo $this->translate('必填'); ?></span></p>
            </a>
        <div class="panel-collapse collapse in">
            <ul class="ect-radio">
                <?php if ($this->payment) {
                foreach($this->payment as $key => $value) {
                ?>
                <li>
                    <input type="radio" name="pyament_code" id="pyament_code_<?php echo $value['editaction']; ?>" <?php if(isset($value['selected']) and $value['selected'] == 1) echo 'checked'; ?> value="<?php echo $value['editaction']; ?>" onclick="calculate_fee('payment_price_<?php echo $value['editaction']; ?>', 'payment', '<?php echo $value['editaction']; ?>');">
                    <label for="pyament_code_<?php echo $value['editaction']; ?>"><i></i> <?php echo $value['payment_name']['content']; ?>&nbsp;[ <strong><?php echo $this->translate('费用'); ?>：<?php echo $this->frontwebsite()->shopPriceSymbol(); ?><span id="payment_price_<?php echo $value['editaction']; ?>"><?php echo $value['payment_fee']['content']; ?></span><?php echo $this->frontwebsite()->shopPriceUnit(); ?></strong> ]</label>
                </li>
                <?php } } ?>
            </ul>
        </div>

        <a class="collapsed">
            <p><b><?php echo $this->translate('送货时间'); ?></b></p>
        </a>
        <div class="panel-collapse collapse in">
            <ul class="ect-radio">
                <li>
                    <input type="radio" name="shipping_time" checked id="shipping_time_<?php echo $this->translate('只工作日送货'); ?>" value="<?php echo $this->translate('只工作日送货'); ?>">
                    <label for="shipping_time_<?php echo $this->translate('只工作日送货'); ?>"><i></i> <?php echo $this->translate('只工作日送货'); ?></label>
                </li>
                <li>
                    <input type="radio" name="shipping_time" id="shipping_time_<?php echo $this->translate('工作日、双休日与假日均可送货'); ?>" value="<?php echo $this->translate('工作日、双休日与假日均可送货'); ?>">
                    <label for="shipping_time_<?php echo $this->translate('工作日、双休日与假日均可送货'); ?>"><i></i> <?php echo $this->translate('工作日、双休日与假日均可送货'); ?></label>
                </li>
                <li>
                    <input type="radio" name="shipping_time" id="shipping_time_<?php echo $this->translate('只双休日、假日送货(工作日不用送)'); ?>" value="<?php echo $this->translate('只双休日、假日送货(工作日不用送)'); ?>">
                    <label for="shipping_time_<?php echo $this->translate('只双休日、假日送货(工作日不用送)'); ?>"><i></i> <?php echo $this->translate('只双休日、假日送货(工作日不用送)'); ?></label>
                </li>
            </ul>
        </div>
        <?php if ($this->frontwebsite()->websiteInfo('shop_invoice') == 'true') { ?>
            <a class="collapsed">
                <p><b><?php echo $this->translate('发票信息'); ?></b></p>
            </a>
            <div class="panel-collapse collapse in">
                <ul class="ect-radio">
                    <li>
                        <select name="navigation_type" class="span6">
                            <option value="<?php echo $this->translate('个人发票'); ?>"><?php echo $this->translate('个人发票'); ?></option>
                            <option value="<?php echo $this->translate('公司发票'); ?>"><?php echo $this->translate('公司发票'); ?></option>
                        </select>
                    </li>
                    <li>
                        <input type="text" class="span3" name="invoice_title" placeholder="<?php echo $this->translate('发票抬头'); ?>" id="invoice_title">
                    </li>
                    <li>
                        <input type="text" class="span4" name="invoice_content" placeholder="<?php echo $this->translate('发票内容'); ?>" id="invoice_content">
                    </li>
                </ul>
            </div>
        <?php } ?>
    </section>

    <section class="ect-margin-tb ect-padding-lr checkout-select">
        <a class="select">
            <p><b> <?php echo $this->translate('买家留言'); ?> </b></p></a>
        <div class="panel-collapse collapse in" id="collapseFive" style="">
            <input type="text" placeholder="<?php echo $this->translate('请输入留言信息'); ?>" class="fuyan" name="order_message" id="order_message">
        </div>
    </section>

    <section class="ect-margin-tb ect-margin-bottom0 ect-padding-lr checkout-select checkout-pro-list">
        <p><b><?php echo $this->translate('商品清单'); ?></b><span class="label ect-bg-colory"><a class="ect-colorf" href="<?php echo $this->url('m_cart/default'); ?>"><?php echo $this->translate('修改'); ?></a></span></p>
        <ul>
            <?php
            $cart_integral_num = 0;//购物车中的积分购买商品数
            foreach ($this->cart_array as $cart_key => $goods_value) {
                $cart_integral_num = $cart_integral_num + $goods_value['integral_num'];
                ?>
            <li>
                <dl>
                    <dt class="pull-left">
                        <a target="_blank" href="<?php echo $this->url('m_goods/default', array('goods_id'=>$goods_value['goods_id'], 'class_id'=>$goods_value['class_id'])); ?>"><?php echo $this->escapeHtml($goods_value['goods_name']); ?></a>
                        <?php
                        if($goods_value['goods_color_name'] == '' and $goods_value['goods_size_name'] == '') {
                            //echo $this->translate('无');
                        } else {
                            echo '<p>';
                            if($goods_value['goods_color_name'] != '') echo $goods_value['goods_color_name'] . '&nbsp;&nbsp;';
                            if($goods_value['goods_size_name'] != '') echo $goods_value['goods_size_name'];
                            echo '</p>';
                        }
                        ?>
                    </dt>
                    <dd class="pull-left list-num">x <?php echo $goods_value['buy_num']; ?></dd>
                    <dd class="pull-right"><?php echo $this->frontwebsite()->shopPriceSymbol().$this->frontwebsite()->shopPrice($goods_value['goods_shop_price'])*$goods_value['buy_num'].$this->frontwebsite()->shopPriceUnit(); ?></dd>
                </dl>
            </li>
            <?php } ?>
        </ul>
        <?php if($this->integralInfo['integralNum'] and $this->integralInfo['integralNum'] > 0) { ?>
            <div class="ect-padding-tb text-right">
                <strong><?php echo $this->translate('消费积分'); if(!empty($this->integralInfo['integalRuleInfo'])) echo '(<font color="#139EE6">' . $this->integralInfo['integalRuleInfo'] . '</font>)'; ?>：<font color="#ED145B"><?php echo $this->integralInfo['integralNum']; echo $this->translate('积分'); ?></font></strong>
            </div>
        <?php } ?>
        <?php if($this->integralInfo1['integralNum'] and $this->integralInfo1['integralNum'] > 0) { ?>
            <div class="ect-padding-tb text-right">
                <strong><?php echo $this->translate('等级积分'); if(!empty($this->integralInfo1['integalRuleInfo'])) echo '(<font color="#139EE6">' . $this->integralInfo1['integalRuleInfo'] . '</font>)'; ?>：<font color="#ED145B"><?php echo $this->integralInfo1['integralNum']; echo $this->translate('积分'); ?></font></strong>
            </div>
        <?php } ?>
        <div class="ect-padding-tb text-right">
            <?php echo $this->translate('商品总价'); ?>:
            <b class="ect-colory"><?php echo $this->frontwebsite()->shopPriceSymbol().$this->frontwebsite()->getCartTotal().$this->frontwebsite()->shopPriceUnit(); ?></b>
            <br>
            <?php echo $this->translate('支付手续费'); ?>：
            <b class="ect-colory"><?php echo $this->frontwebsite()->shopPriceSymbol(); ?><span id="pay_fee"><?php if(isset($this->payment[0]['payment_fee']['content'])) echo $this->payment[0]['payment_fee']['content']; else echo '0'; ?></span><?php echo $this->frontwebsite()->shopPriceUnit(); ?></b>
            <br>
            <?php echo $this->translate('购买优惠'); ?>：
            <font color="#ED145B">-<?php echo $this->frontwebsite()->shopPriceSymbol(); ?><span id="buy_pre_fee"><?php echo isset($this->promotionsCost) ? $this->promotionsCost : 0; ?></span><?php echo $this->frontwebsite()->shopPriceUnit(); ?></font>
            <br>
            <?php echo $this->translate('会员优惠'); ?>：
            <font color="#ED145B">-<?php echo $this->frontwebsite()->shopPriceSymbol(); ?><span id="user_pre_fee">0</span><?php echo $this->frontwebsite()->shopPriceUnit(); ?></font>
            <br>
            <?php if ($cart_integral_num > 0) { ?>
                <?php echo $this->translate('积分购买'); ?>：
                <font color="#ED145B">-<?php echo $this->frontwebsite()->shopPriceSymbol(); ?><span id="user_integral_buy">0</span><?php echo $this->frontwebsite()->shopPriceUnit(); ?></font>
                <br>
            <?php } ?>
            <?php echo $this->translate('应付款金额'); ?>: <b class="ect-colory"><?php echo $this->frontwebsite()->shopPriceSymbol(); ?><span id="order_total_fee"><?php echo $this->order_total; ?></span><?php echo $this->frontwebsite()->shopPriceUnit(); ?></b><br>

            <input type="hidden" id="user_pre_price" name="user_pre_price" value="0" />
            <input type="hidden" id="user_integral_price" name="user_integral_price" value="0" />
            <input type="hidden" id="buy_pre_price" name="buy_pre_price" value="<?php echo isset($this->promotionsCost) ? $this->promotionsCost : 0; ?>" />
            <input type="hidden" id="express_price" name="express_price" value="<?php if(isset($this->express_array[0]['express_price'])) echo $this->frontwebsite()->shopPrice($this->express_array[0]['express_price']); else echo '0'; ?>" />
            <input type="hidden" id="pay_price" name="pay_price" value="<?php if(isset($this->payment[0]['payment_fee']['content'])) echo $this->payment[0]['payment_fee']['content']; else echo '0'; ?>" />
            <input type="hidden" id="goods_total_price" name="goods_total_price" value="<?php echo $this->frontwebsite()->getCartTotal(); ?>" />
            <input type="hidden" id="order_total_price" name="order_total_price" value="<?php echo $this->order_total; ?>" />
            <input type="hidden" id="goods_count_weight" name="goods_count_weight" value="<?php if ($this->total_weight > 0) echo $this->total_weight; else echo 0; ?>" />
        </div>

    </section>

    <div class="ect-padding-lr ect-padding-tb ect-margin-tb">
        <?php if(!empty($this->payment)) { ?>
        <input type="submit" class="btn btn-info ect-btn-info ect-colorf ect-bg" value="<?php echo $this->translate('订单提交'); ?>" name="submit">
        <?php } ?>
        <input type="hidden" name="step" value="stepvirtual" />
    </div>
    </form>
</div>

<script>
    function calculate_fee(input_id, type, paymentcode) {
        var html_price = $('#'+input_id).html();

        <?php if(isset($this->user_info->user_integral_num) and $this->user_info->user_integral_num > 0 and $cart_integral_num > 0) { ?>
        var integral_num = $('#integral_buy_num').val();
        if(integral_num == '') integral_num = 0;
        var re = /^[0-9]+.?[0-9]*$/;
        if(!re.test(integral_num)) {
            alert('<?php echo $this->translate('积分必须为数字'); ?>'); $('#'+input_id).val(0);
            integral_num = 0;
        } else {
            if(integral_num > 0) {
                if(integral_num > <?php echo $this->user_info->user_integral_num; ?>) {
                    alert('<?php echo $this->translate('输入的积分数量超过了您拥有的积分数！'); ?>');
                    $('#'+input_id).val(0);
                    integral_num = 0;
                }
                if(integral_num > <?php echo $cart_integral_num; ?>) {
                    alert('<?php echo $this->translate('输入的积分数量超过了订单中可用积分购买的最大量！'); ?>');
                    $('#'+input_id).val(0);
                    integral_num = 0;
                }
                //从这里开始，integral_num 变成了积分转换后的货币值
                integral_num = accMul(integral_num, <?php echo $this->integral_currency_con; ?>);
                var con_order_total = accAdd(parseFloat($('#order_total_price').val()), parseFloat($('#user_integral_price').val()));
                if(integral_num > con_order_total) {
                    alert('<?php echo $this->translate('输入的积分数量超过订单应付总额，请重新输入！'); ?>');
                    $('#'+input_id).val(0);
                    integral_num = 0;
                }
            }
        }
        <?php } ?>

        if(type == 'express') {
            $('#express_price').val(html_price);
            $('#express_fee').html(html_price);
        } else if (type == 'payment') {
            $('#pay_price').val(html_price);
            $('#pay_fee').html(html_price);

            if(paymentcode == 'hdfk') {
                $('.no_cash_on_delivery').css('display', 'none');
            } else {
                $('.no_cash_on_delivery').css('display', '');
            }
        } else if (type == 'integral') {//积分购买
            $('#user_integral_price').val(integral_num);
            $('#user_integral_buy').html(integral_num);
        }

        order_total = 0;
        order_total = accAdd(order_total, parseFloat($('#express_price').val()));
        order_total = accAdd(order_total, parseFloat($('#pay_price').val()));
        order_total = accAdd(order_total, parseFloat($('#goods_total_price').val()));

        order_total = Subtr(order_total, parseFloat($('#buy_pre_price').val()));
        order_total = Subtr(order_total, parseFloat($('#user_pre_price').val()));

        <?php if(isset($this->user_info->user_integral_num) and $this->user_info->user_integral_num > 0 and $cart_integral_num > 0) { ?>
        order_total = Subtr(order_total, parseFloat($('#user_integral_price').val()));
        <?php } ?>

        order_total = advFormatNumber(order_total, 2);

        $('#order_total_price').val(order_total);
        $('#order_total_fee').html(order_total);
    }
</script>