<div class="navbar navbar-static-top">
	<div class="navbar-inner">
    	<a href="<?php echo $this->url('adminHome/default',array('action'=>'index','controller'=>'home')); ?>" class="brand">DBShop</a>
		<ul class="nav">
            <li class="dropdown <?php if($this->myviewalias()->returnNamespace() == 'Analytics\Controller') echo 'active'; ?>"><a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->translate('统计分析'); ?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li <?php if($this->page_type == 'userStats') echo 'class="active"'; ?>><a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'userStats')); ?>"><?php echo $this->translate('客户统计'); ?></a></li>
                    <li <?php if($this->page_type == 'usersOrder') echo 'class="active"'; ?>><a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'usersOrder')); ?>"><?php echo $this->translate('客户排行'); ?></a></li>
                    <li <?php if($this->page_type == 'orderStats') echo 'class="active"'; ?>><a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'orderStats')); ?>"><?php echo $this->translate('订单统计'); ?></a></li>
                    <li <?php if($this->page_type == 'saleStats') echo 'class="active"'; ?>><a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'saleStats')); ?>"><?php echo $this->translate('销售概况'); ?></a></li>
                    <li <?php if($this->page_type == 'saleList') echo 'class="active"'; ?>><a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'saleList')); ?>"><?php echo $this->translate('销售明细'); ?></a></li>
                    <li <?php if($this->page_type == 'saleOrder') echo 'class="active"'; ?>><a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'saleOrder')); ?>"><?php echo $this->translate('销售排行'); ?></a></li>
                    <?php
                    $shop_tongji_type = $this->frontwebsite()->websiteInfo('shop_tongji_type');
                    $shop_tongji_token= $this->frontwebsite()->websiteInfo('shop_tongji_token');
                    if($shop_tongji_type == 'baidu' and !empty($shop_tongji_token)) { ?>
                        <li><a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics')); ?>"><?php echo $this->translate('流量概况'); ?></a></li>
                        <li><a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'trand')); ?>"><?php echo $this->translate('趋势分析'); ?></a></li>
                        <!--li><a href="<?php echo $this->url('analytics/default'); ?>"><?php echo $this->translate('全部来源'); ?></a></li>
                        <li><a href="<?php echo $this->url('analytics/default'); ?>"><?php echo $this->translate('搜索引擎'); ?></a></li>
                        <li><a href="<?php echo $this->url('analytics/default'); ?>"><?php echo $this->translate('搜索词语'); ?></a></li>
                        <li><a href="<?php echo $this->url('analytics/default'); ?>"><?php echo $this->translate('地域分布'); ?></a></li>
                        <li><a href="<?php echo $this->url('analytics/default'); ?>"><?php echo $this->translate('系统环境'); ?></a></li>
                        <li><a href="<?php echo $this->url('analytics/default'); ?>"><?php echo $this->translate('新老访客'); ?></a></li>-->
                    <?php } else { ?>
                    <li><a href="<?php echo $this->url('system/default',array('controller'=>'system')); ?>"><?php echo $this->translate('统计设置'); ?></a></li>
                    <?php } ?>
                </ul>
            </li>

            <li class="dropdown <?php if($this->myviewalias()->returnNamespace() == 'Orders\Controller') echo 'active'; ?>"><a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->translate('销售管理'); ?> <b class="caret"></b></a>
            	<ul class="dropdown-menu">
                	<li><a href="<?php echo $this->url('orders/default'); ?>"><?php echo $this->translate('订单管理'); ?></a></li>
                	<li><a href="<?php echo $this->url('orders/default', array('action'=>'shiplist', 'controller'=>'Orders')); ?>"><?php echo $this->translate('发货单'); ?></a></li>
                	<li><a href="<?php echo $this->url('orders/default', array('action'=>'paylog', 'controller'=>'Orders')); ?>"><?php echo $this->translate('支付记录'); ?></a></li>
                	<li><a href="<?php echo $this->url('orders/default', array('action'=>'refund', 'controller'=>'Orders')); ?>"><?php echo $this->translate('退货管理'); ?></a></li>
                    <li><a href="<?php echo $this->url('orders/default', array('action'=>'expressNumber', 'controller'=>'Orders')); ?>"><?php echo $this->translate('快递单号管理'); ?></a></li>
                </ul>
            </li>
            <li class="dropdown <?php if($this->myviewalias()->returnNamespace() == 'Goods\Controller') echo 'active'; ?>"><a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->translate('商品管理'); ?> <b class="caret"></b></a>
            	<ul class="dropdown-menu">
                	<li><a href="<?php echo $this->url('goods/default',array('controller'=>'goods')); ?>"><?php echo $this->translate('管理商品'); ?></a></li>
                    <li><a href="<?php echo $this->url('class/default',array('controller'=>'class')); ?>"><?php echo $this->translate('管理分类'); ?></a></li>
                	<li class="dropdown-submenu">
                    <a href="#"><?php echo $this->translate('商品属性'); ?></a>
                    	<ul class="dropdown-menu">
                        	<li><a href="<?php echo $this->url('attribute/default'); ?>"><?php echo $this->translate('属性'); ?></a></li>
                            <li><a href="<?php echo $this->url('attribute/default',array('action'=>'attributeGroup')); ?>"><?php echo $this->translate('属性分组'); ?></a></li>
                        </ul>
                    </li>
                    <li><a href="<?php echo $this->url('brand/default',array('controller'=>'brand')); ?>"><?php echo $this->translate('商品品牌'); ?></a></li>
                    <li><a href="<?php echo $this->url('comment/default',array('controller'=>'comment')); ?>"><?php echo $this->translate('商品评价'); ?></a></li>
                    <li><a href="<?php echo $this->url('ask/default'); ?>"><?php echo $this->translate('商品咨询'); ?></a></li>
                	<li class="dropdown-submenu">
                    <a href="#"><?php echo $this->translate('商品标签'); ?></a>
                    	<ul class="dropdown-menu">
                        	<li><a href="<?php echo $this->url('tag/default',array('controller'=>'tag')); ?>"><?php echo $this->translate('普通商品标签'); ?></a></li>
                        	<li><a href="<?php echo $this->url('tag/default',array('controller'=>'tag', 'action'=>'specTag')); ?>"><?php echo $this->translate('特定商品标签'); ?></a></li>
                            <li><a href="<?php echo $this->url('tag/default',array('controller'=>'tag', 'action'=>'tagGroup')); ?>"><?php echo $this->translate('商品标签分组'); ?></a></li>
                        </ul>
                    </li>
                    <li><a href="<?php echo $this->url('promotions/default'); ?>"><?php echo $this->translate('优惠促销规则'); ?></a></li>
                    <li><a href="<?php echo $this->url('goods/default', array('action'=>'goodsIndex')); ?>"><?php echo $this->translate('商品索引'); ?></a></li>
                </ul>
            </li>
            <li class="dropdown <?php if($this->myviewalias()->returnNamespace() == 'User\Controller') echo 'active'; ?>"><a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->translate('客户管理'); ?> <b class="caret"></b></a>
            	<ul class="dropdown-menu">
                	<li><a href="<?php echo $this->url('user/default',array('controller'=>'user')); ?>"><?php echo $this->translate('管理客户'); ?></a></li>
                    <li><a href="<?php echo $this->url('usergroup/default',array('controller'=>'usergroup')); ?>"><?php echo $this->translate('管理客户组'); ?></a></li>
                    <li class="dropdown-submenu">
                        <a href="#"><?php echo $this->translate('客户余额'); ?></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('usermoney/default',array('action'=>'paycheck')); ?>"><?php echo $this->translate('充值记录'); ?></a></li>
                            <li><a href="<?php echo $this->url('usermoney/default',array('action'=>'withdraw')); ?>"><?php echo $this->translate('提现申请'); ?></a></li>
                            <li><a href="<?php echo $this->url('usermoney/default',array('action'=>'index')); ?>"><?php echo $this->translate('余额记录'); ?></a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                    <a href="#"><?php echo $this->translate('管理积分'); ?></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('integral/default',array('action'=>'integralType')); ?>"><?php echo $this->translate('积分类型'); ?></a></li>
                            <li><a href="<?php echo $this->url('integral/default',array('action'=>'integrallog')); ?>"><?php echo $this->translate('积分历史记录'); ?></a></li>
                            <li><a href="<?php echo $this->url('integral/default',array('action'=>'integralRule')); ?>"><?php echo $this->translate('积分规则'); ?></a></li>
                        </ul>                    
                    </li>
                    <!-- <li><a href="<?php echo $this->url('userintegration/default'); ?>"><?php echo $this->translate('管理整合'); ?></a></li> -->
                </ul>            
            </li>
            <li class="dropdown <?php if($this->myviewalias()->returnNamespace() == 'Cms\Controller') echo 'active'; ?>"><a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->translate('CMS管理'); ?> <b class="caret"></b></a>
             	<ul class="dropdown-menu">
                	<li><a href="<?php echo $this->url('cms/default', array('controller'=>'Cms')); ?>"><?php echo $this->translate('管理文章'); ?></a></li>
                    <li><a href="<?php echo $this->url('cms/default', array('controller'=>'Class')); ?>"><?php echo $this->translate('管理文章分类'); ?></a></li>
                    <li><a href="<?php echo $this->url('cms/default', array('controller'=>'Cms', 'action'=>'singleArticle')); ?>"><?php echo $this->translate('管理单页文章'); ?></a></li>
                </ul>           
            </li>
            <li class="dropdown <?php if(in_array($this->myviewalias()->returnNamespace(), array('Navigation\Controller', 'Links\Controller', 'Upload\Controller', 'Email\Controller', 'Ad\Controller', 'Dbsql\Controller', 'Operlog\Controller', 'Errorlog\Controller'))) echo 'active'; ?>"><a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->translate('工具管理'); ?> <b class="caret"></b></a>
             	<ul class="dropdown-menu">
             	    <li><a href="<?php echo $this->url('navigation/default'); ?>"><?php echo $this->translate('导航设置'); ?></a></li>
                	<li><a href="<?php echo $this->url('links/default'); ?>"><?php echo $this->translate('友情链接'); ?></a></li>
                    <li><a href="<?php echo $this->url('email/default'); ?>"><?php echo $this->translate('邮件发送'); ?></a></li>
                    <li class="dropdown-submenu">
                        <a href="#"><?php echo $this->translate('广告管理'); ?></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('ad/default'); ?>"><?php echo $this->translate('电脑端广告(PC)'); ?></a></li>
                            <li><a href="<?php echo $this->url('ad/default',array('action'=>'mobileIndex')); ?>"><?php echo $this->translate('手机端广告(Phone)'); ?></a></li>
                        </ul>
                    </li>
                    <li><a href="<?php echo $this->url('dbsql/default'); ?>"><?php echo $this->translate('数据库备份'); ?></a></li>
                    <li><a href="<?php echo $this->url('operlog/default'); ?>"><?php echo $this->translate('操作日志'); ?></a></li>
                    <!-- <li><a href="<?php echo $this->url('errorlog/default'); ?>"><?php echo $this->translate('错误日志'); ?></a></li> -->
                </ul>             
            </li>
            <li class="dropdown <?php if(in_array($this->myviewalias()->returnNamespace(),array('Region\Controller','System\Controller','Package\Controller', 'Express\Controller', 'Payment\Controller', 'Currency\Controller', 'Template\Controller')) or in_array($this->myviewalias()->returnControllername(),array('Admin\Controller\Admin', 'Orders\Controller\State', 'Stock\Controller\State'))) echo 'active'; ?>"><a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->translate('系统管理'); ?> <b class="caret"></b></a>
             	<ul class="dropdown-menu">
                	<li><a href="<?php echo $this->url('system/default',array('controller'=>'system')); ?>"><?php echo $this->translate('系统设置'); ?></a></li>
                    <li><a href="<?php echo $this->url('optimization/default',array('controller'=>'optimization', 'action'=>'index')); ?>"><?php echo $this->translate('性能优化'); ?></a></li>
                    <li><a href="<?php echo $this->url('system/default',array('controller'=>'system', 'action'=>'uploadset')); ?>"><?php echo $this->translate('附件设置'); ?></a></li>
                    <li><a href="<?php echo $this->url('system/default',array('controller'=>'system', 'action'=>'userset')); ?>"><?php echo $this->translate('客户设置'); ?></a></li>
                    <!--<li><a href=""><?php echo $this->translate('语言设置'); ?></a></li>-->
                    <li><a href="<?php echo $this->url('currency/default',array('action'=>'index')); ?>"><?php echo $this->translate('货币设置'); ?></a></li>
                    <li><a href="<?php echo $this->url('payment/default',array('action'=>'index')); ?>"><?php echo $this->translate('支付设置'); ?></a></li>
                    <li class="dropdown-submenu">
                    <a href="#"><?php echo $this->translate('配送设置'); ?></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('express/default',array('action'=>'index')); ?>"><?php echo $this->translate('配送设置'); ?></a></li>
                            <li><a href="<?php echo $this->url('express/default',array('action'=>'expressapi')); ?>"><?php echo $this->translate('动态API'); ?></a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                        <a href="#"><?php echo $this->translate('消息提醒设置'); ?></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('system/default',array('controller'=>'system', 'action'=>'phoneMessageSet')); ?>"><?php echo $this->translate('手机短信提醒设置'); ?></a></li>
                            <li><a href="<?php echo $this->url('system/default',array('controller'=>'system', 'action'=>'sendMessageSet')); ?>"><?php echo $this->translate('电子邮件提醒设置'); ?></a></li>
                        </ul>
                    </li>
                    <li><a href="<?php echo $this->url('region/default',array('controller'=>'region')); ?>"><?php echo $this->translate('地区管理'); ?></a></li>
                	<li class="dropdown-submenu">
                	<a href="#"><?php echo $this->translate('状态设置'); ?></a>
                	   <ul class="dropdown-menu">
                	       <li><a href="<?php echo $this->url('stock_state/default'); ?>"><?php echo $this->translate('库存状态'); ?></a></li>
                	   </ul>
                	</li>
                	<li class="dropdown-submenu">
                    <a href="#"><?php echo $this->translate('管理员设置'); ?></a>
                    	<ul class="dropdown-menu">
                        	<li><a href="<?php echo $this->url('admin/default',array('action'=>'administrator')); ?>"><?php echo $this->translate('管理员'); ?></a></li>
                            <li><a href="<?php echo $this->url('admin/default',array('action'=>'admingroup')); ?>"><?php echo $this->translate('管理员组'); ?></a></li>
                        </ul>
                    </li>
                	<li class="dropdown-submenu">
                	<a href="#"><?php echo $this->translate('在线客服设置'); ?></a>
                	   <ul class="dropdown-menu">
                           <li><a href="<?php echo $this->url('online/default', array('action'=>'onlineStyle')); ?>"><?php echo $this->translate('客服样式设置'); ?></a></li>
                           <li><a href="<?php echo $this->url('online/default', array('action'=>'group')); ?>"><?php echo $this->translate('在线客服分组'); ?></a></li>
                           <li><a href="<?php echo $this->url('online/default'); ?>"><?php echo $this->translate('在线客服成员'); ?></a></li>
                	   </ul>
                	</li>
                	<li><a href="<?php echo $this->url('template/default'); ?>"><?php echo $this->translate('模板管理'); ?></a></li>
                    <li><a href="<?php echo $this->url('package/default',array('action'=>'index')); ?>"><?php echo $this->translate('系统更新'); ?></a></li>
                </ul>           
            </li>
        </ul>
        <ul class="nav pull-right">
        	<li class="<?php if($this->myviewalias()->returnControllername() == 'Admin\Controller\Home') echo 'active'; ?>" ><a href="<?php echo $this->url('adminHome/default',array('action'=>'index','controller'=>'home')); ?>"><?php echo $this->translate('后台首页'); ?></a></li>
            <li class="divider-vertical"></li>
            <li><a href="<?php echo $this->url('shopfront/default'); ?>" target="_blank" style=" padding:10px 1px;"><?php echo $this->translate('前台首页'); ?></a></li>
        </ul>
    </div>
</div>
<div class="row-fluid">
	<div class="span12">
    	<div class="well" style="background: #FFF;padding:0px 15px 12px 15px;">
    	<p style="margin:3px 0 0 0;" class="pull-left"><i class="icon-ban-circle"></i><!-- <i class="icon-volume-up"></i> --><?php echo $this->translate('暂无新消息'); ?></p>
        <p style="margin:3px 0 0 0;" class="pull-right"><?php echo $this->myviewalias()->returnAuth('admin_group_name'); ?>：<a href="<?php echo $this->url('admin/default/admin_id',array('action'=>'adminedit','controller'=>'admin','admin_id'=>$this->myviewalias()->returnAuth('admin_id'))); ?>"><?php echo $this->myviewalias()->returnAuth('admin_name'); ?></a>&nbsp;&nbsp;<?php $weekArray=array(1=>$this->translate('星期一'), 2=>$this->translate('星期二'), 3=>$this->translate('星期三'), 4=>$this->translate('星期四'), 5=>$this->translate('星期五'), 6=>$this->translate('星期六'), 0=>$this->translate('星期日')); $timeStr = time(); echo date("Y-m-d", $timeStr).' '.$weekArray[date("w", $timeStr)]; ?>
            <?php if(defined('FRONT_CACHE_STATE') and FRONT_CACHE_STATE == 'true') { ?>
            &nbsp;&nbsp;<a href="javascript:;" onclick="clear_front_cache();" class="btn btn-small btn-primary"><i class="icon-trash icon-white"></i> <?php echo $this->translate('缓存清理'); ?></a>
            <?php } ?>
            &nbsp;&nbsp;<a href="<?php echo $this->url('admin/default',array('action'=>'loginout','controller'=>'index')); ?>" class="btn btn-small btn-danger"><i class="icon-off icon-white"></i> <?php echo $this->translate('退出系统'); ?></a>
        </p>
        <?php if(defined('FRONT_CACHE_STATE') and FRONT_CACHE_STATE == 'true') { ?>
        <script>
            function clear_front_cache() {
                $.post("<?php echo $this->url('optimization/default',array('controller'=>'optimization', 'action'=>'clearFrontCache')); ?>",'',
                    function(data){
                        if(data == 'true') {
                            alert('<?php echo $this->translate('缓存清理完毕！'); ?>');
                        } else {
                            alert('<?php echo $this->translate('缓存清理失败！'); ?>');
                        }
                    });
            }
        </script>
        <?php } ?>
        </div>
        <div  class="admin_body">