<form class="validforms" enctype="multipart/form-data" method="post" name="user_edit_form" id="user_edit_form">
<section class="flow-consignee ect-bg-colorf">
    <ul>
        <li>
            <div class="input-text"><b class="pull-left"><?php echo $this->translate('用户名称'); ?>：</b><span>
                <?php echo $this->escapeHtml($this->user_info->user_name); ?>
          </span></div>
        </li>
        <?php
        $userEmailRegisterState = $this->frontwebsite()->getRegOrLoginIni('register_email_state');
        $userPhoneRegisterState = $this->frontwebsite()->getRegOrLoginIni('register_phone_state');
        ?>
        <li>
            <div class="input-text"><b class="pull-left"><?php echo $this->translate('电子邮件'); ?>
                    <?php if ($userEmailRegisterState == 'true') { ?>
                        <span class="must_add_value">*</span>
                    <?php } ?>
                    ：</b><span>
          <input type="text" datatype="e" value="<?php echo $this->user_info->user_email; ?>" ajaxurl="<?php echo $this->url('m_user/default/user_id',array('action'=>'check','controller'=>'user','module'=>'user','check_type'=>'user_email','user_id'=>($this->user_info ? $this->user_info->user_id : '0'))); ?>" placeholder="<?php echo $this->translate('请输入电子邮箱'); ?>" <?php if($userEmailRegisterState == 'true') echo 'nullmsg="'.$this->translate('请输入电子邮箱').'"'; ?> name="user_email">
          </span></div>
        </li>
        <li>
            <div class="input-text"><b class="pull-left"><?php echo $this->translate('手机号码'); ?>
                    <?php if ($userPhoneRegisterState == 'true') { ?>
                        <span class="must_add_value">*</span>
                    <?php } ?>
                    ：</b><span>
          <input type="text"  datatype="m" value="<?php echo $this->user_info->user_phone; ?>" ajaxurl="<?php echo $this->url('m_user/default/user_id',array('action'=>'check','controller'=>'user','module'=>'user','check_type'=>'user_phone','user_id'=>($this->user_info ? $this->user_info->user_id : '0'))); ?>" placeholder="<?php echo $this->translate('请输入手机号码'); ?>"  name="user_phone" <?php if($userPhoneRegisterState == 'true') echo 'nullmsg="'.$this->translate('请输入手机号码').'"'; ?> errormsg="<?php echo $this->translate('手机号码格式错误'); ?>">
          </span></div>
        </li>
    </ul>
</section>

<div class="two-btn ect-padding-tb ect-padding-lr ect-margin-tb text-center">
    <input type="submit" class="btn btn-info" value="<?php echo $this->translate('确认修改'); ?>" name="submit">
</div>
</form>