<div class="row-fluid" id="list_location">
	<div class="span10 offset1">
    	<a href="<?php echo $this->url('shopfront/default'); ?>"><?php echo $this->translate('首页'); ?></a> <span class="divider">&gt;</span> <?php if(isset($this->keywords)) echo $this->escapeHtml($this->keywords); ?> 
    </div>
</div>

<div class="row-fluid" id="goods_list">
    <div class="row span10 offset1">
        <div class="span12 goods_img_list">
        <div class="span12 goods_img_list_line">
    <?php
		$serach_key   = $this->keywords != '' ? '&keywords=' . $this->keywords : '';
		$sort_c_str   = ($this->sort_c != '' ? '&sort_c=' . $this->sort_c : '') . $serach_key;
	?>
    	   <div class="span8">
        	<div class="btn-group">
          		<button data-toggle="dropdown" class="btn dropdown-toggle"><?php echo $this->translate('价格'); ?> <span class="caret"></span></button>
          		<ul class="dropdown-menu">
            		<li><a href="?price_sort=ASC<?php echo $sort_c_str; ?>"><?php echo $this->translate('价格上升'); ?><?php if(isset($this->sort_selected) and $this->sort_selected == 'goods_shop_priceASC') echo '&nbsp;<i class="icon-ok"></i>'; ?></a></li>
            		<li><a href="?price_sort=DESC<?php echo $sort_c_str; ?>"><?php echo $this->translate('价格下降'); ?><?php if(isset($this->sort_selected) and $this->sort_selected == 'goods_shop_priceDESC') echo '&nbsp;<i class="icon-ok"></i>'; ?></a></li>
          		</ul>
       	 	</div>
        	<div class="btn-group">
          		<button data-toggle="dropdown" class="btn dropdown-toggle"><?php echo $this->translate('人气'); ?> <span class="caret"></span></button>
          		<ul class="dropdown-menu">
            		<li><a href="?click_sort=ASC<?php echo $sort_c_str; ?>"><?php echo $this->translate('人气上升'); ?><?php if(isset($this->sort_selected) and $this->sort_selected == 'goods_clickASC') echo '&nbsp;<i class="icon-ok"></i>'; ?></a></li>
            		<li><a href="?click_sort=DESC<?php echo $sort_c_str; ?>"><?php echo $this->translate('人气下降'); ?><?php if(isset($this->sort_selected) and $this->sort_selected == 'goods_clickDESC') echo '&nbsp;<i class="icon-ok"></i>'; ?></a></li>
          		</ul>
       	 	</div>
        	<div class="btn-group">
          		<button data-toggle="dropdown" class="btn dropdown-toggle"><?php echo $this->translate('上架时间'); ?> <span class="caret"></span></button>
          		<ul class="dropdown-menu">
            		<li><a href="?time_sort=ASC<?php echo $sort_c_str; ?>"><?php echo $this->translate('时间上升'); ?><?php if(isset($this->sort_selected) and $this->sort_selected == 'goods_add_timeASC') echo '&nbsp;<i class="icon-ok"></i>'; ?></a></li>
            		<li><a href="?time_sort=DESC<?php echo $sort_c_str; ?>"><?php echo $this->translate('时间下降'); ?><?php if(isset($this->sort_selected) and $this->sort_selected == 'goods_add_timeDESC') echo '&nbsp;<i class="icon-ok"></i>'; ?></a></li>
          		</ul>
       	 	</div> 
           </div>
           <div class="span4">            
            <span class="pull-right"><?php echo $this->translate('共'); ?> <font color="#ED154B"><?php echo $this->goods_list->getTotalItemCount(); ?><?php echo $this->translate('个'); ?></font> <?php echo $this->translate('商品'); ?>&nbsp;&nbsp;</span>
           </div>
        </div>
        <div class="well" id="right_goods_list">
        	<ul class="thumbnails">
            	<?php if ($this->goods_list->getTotalItemCount() > 0) { foreach ($this->goods_list as $goods_value) { ?>
            	<li class="span3">
                <a target="_blank" class="thumbnail" title="<?php echo $this->escapeHtml($goods_value['goods_name']); ?>" href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$goods_value['goods_id'], 'class_id'=>$goods_value['one_class_id'])); ?>"><img src="<?php echo $this->basePath($this->frontwebsite()->shopGoodsImage($goods_value['goods_thumbnail_image'])); ?>" border="0"></a>
                <p class="goods_title link_googds_name"><a target="_blank" href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$goods_value['goods_id'], 'class_id'=>$goods_value['one_class_id'])); ?>"><?php echo $this->escapeHtml($goods_value['goods_name']); ?></a></p>
                <?php if ($goods_value['goods_extend_name'] != '') { ?>
                <p class="goods_title extend_goods_name" style="color: #ed145b;"><?php echo $this->escapeHtml($goods_value['goods_extend_name']); ?></p>
                <?php } ?>
                <p><?php echo $this->translate('价格');?>:<strong class="goods_price"><?php echo $this->frontwebsite()->shopPriceExtend($goods_value['goods_shop_price']); ?></strong></p>
                </li>
                <?php } } else { echo '<li>' . $this->translate('没有找到匹配的商品！') . '</li>'; } ?>
            </ul>
        </div>
        		<?php echo ( count($this->goods_list) > 0 ) ? $this->paginationControl($this->goods_list, 'Sliding', 'site/dbpage',array('page_url'=>$this->url('frontgoodslist/default',array('action'=>'goodsSearch', 'class_id'=>0)))) : ""; ?>
        </div>
    </div>
    
     
</div>