<div style="overflow:hidden; position:relative;" class="tempWrap">
    <ul style="width: 600px; position: relative; overflow: hidden; padding: 0px; margin: 0px; transition-duration: 200ms; transform: translateX(0px);">
        <dbshop>
            <li style="display: table-cell; vertical-align: top; width: 600px;"><a target="_blank" href="{ad_url}"><img width="360" border="0" src="{image}"></a></li>
            <dbshop>
    </ul>
</div>